### ISSUE TITLE
Error: undefined is not an object (evaluating 'appState.remove');

### ISSUE THREAD

**Issue by DIUSII** [amrlabib/react-native-appstate-hook#14]
<img width="726" alt="Снимок экрана 2021-10-08 в 20 44 11" src="https://user-images.githubusercontent.com/49521201/136567889-c58481d1-3000-434e-a30a-5251e43c914c.png">

![photo_2021-10-08_20-46-35](https://user-images.githubusercontent.com/49521201/136568319-aa7f5578-9bd2-4e13-9d5c-2ed5e0b0f8a9.jpg)

whats wrong

**Comment by cryptoman04** [comment]
Use version 1.0.5 of this module. Looks like the latest version is only compatible with react-native v0.65 due to the use of the `.remove()` method.

https://github.com/amrlabib/react-native-appstate-hook/blob/v1.0.5/dist/index.js

**Comment by hirbod** [comment]
I can confirm for now, that 1.0.5 is working and 1.0.6 is breaking!

**Comment by hirbod** [comment]
Why are you closing this? The issue is not resolved

**Comment by DIUSII** [comment]
> Why are you closing this? The issue is not resolved

@cryptoman04 help me, because i closed

**Comment by dennisbouwpas** [comment]
@RikSchefferOberon @DIUSII 
I faced same issue, and I have a little typescript solution, take a look guys 
```javascript
import React from 'react';
import { AppState, AppStateStatus } from 'react-native';

interface IUseAppState {
  onChange?: (state: AppStateStatus) => void;
  onForeground?: () => void;
  onBackground?: () => void;
}

export default function useAppState(settings: IUseAppState) {
  const { onChange, onForeground, onBackground } = settings || {};

  const appState = React.useRef<AppStateStatus>(AppState.currentState);
  const [appStateVisible, setAppStateVisible] = React.useState<AppStateStatus>(appState.current);

  const handleAppStateChange = (nextAppState: AppStateStatus) => {
    if (nextAppState === 'active' && appState.current !== 'active') {
      if (onForeground) {
        onForeground();
      }
    } else if (appState.current === 'active' && nextAppState.match(/inactive|background/)) {
      if (onBackground) {
        onBackground();
      }
    }

    appState.current = nextAppState;
    setAppStateVisible(appState.current);
    if (onChange) {
      onChange(nextAppState);
    }
  };

  React.useEffect(() => {
    const subs = AppState.addEventListener('change', handleAppStateChange);

    return () => {
      subs.remove();
    };
  }, []);
  return { appStateVisible };
}
```

and later you can use it same way 
```javascript
useAppState({
    onForeground: () => {},
    etc...
  });
```
