### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by bragovo** [amrlabib/react-native-appstate-hook#7]
Thanks for this package =)

But there is warning a `react-native-appstate-hook@1.0.3" has incorrect peer dependency "react-native@0.59.0-rc.1"`, it's not a big deal, but is it possible to update on `"react-native": "0.61.0"`?

**Comment by crobinson42** [comment]
bump

**Comment by crobinson42** [comment]
#8

**Comment by amrlabib** [comment]
@bragovo  and @crobinson42  Thank you for the issue and PR, it should be fixed in the new version 1.0.4
